### ISSUE TITLE
Uses incorrect docker package name on Ubuntu 20.04

### ISSUE THREAD

**Issue by mrweiner** [lando/hyperdrive#15]
**Describe the bug**
Hyderdrive throws `E: Unable to locate package docker-engine` when running the release script on Ubuntu 20.04 LTS. The docker package is already present on Ubuntu as `docker.io`.

**Comment by mrweiner** [comment]
Okay, seems like this may have to do with lando directly and not hyperdrive. Was able to get docker-ce installed by following: https://linuxize.com/post/how-to-install-and-use-docker-on-ubuntu-20-04/

1. sudo apt update
2. sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
3. curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
4. sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
5. sudo apt update
6. sudo apt install docker-ce docker-ce-cli containerd.io

**Comment by jcandan** [comment]
This worked for me. Only additional note I might add was the need to set user group to docker.

1. Create the docker group.

   > **Note:** This may have already occurred during the Hyperdrive attempt.

   ```
   $ sudo groupadd docker
   ```

2. Add your user to the docker group.

   ```
   $ sudo usermod -aG docker $USER
   ```

3. Activate your user to the docker group.

   ```
   $ newgrp docker
   ```

4. Check if docker can be run without root

   > **Note:** As seen in [Rules to keep your setup easy and happy](https://docs.lando.dev/guides/setup-lando-on-windows-with-wsl-2.html#rules-to-keep-your-setup-easy-and-happy), You have to start Docker every time you start up the WSL2 instance. Running `lando start` should automatically start Docker, but if you need to initialize Docker for non-Lando purposes, try running `sudo service docker start`. This is because the WSL2 distros have no init system, so Docker doesn't auto start.

   ```
   $ docker run hello-world
   ```

If a problem arises, you may need to logout of terminal or reboot to establish your user group.

Source: https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue for details.
