### ISSUE TITLE
Using an unsupported version of DOCKER ENGINE

### ISSUE THREAD

**Issue by iKlsR** [lando/hyperdrive#19]
Installed latest version under wsl2 just now and it seems this needs updating. Not sure if this is something we have control over at install time...

> You have version 18.0.0 but Lando wants something in the 18.09.3 - 20.10.99 range.
   If you have purposefully installed an unsupported version and know what you are doing
   you can probably ignore this warning. If not we recommend you use a supported version
   as this ensures we can provide the best support and stability.
   https://docs.docker.com/engine/install/

**Comment by marklabrecque** [comment]
+1 to this issue, on WSL2

**Comment by iKlsR** [comment]
@pirog No comment?

**Comment by pirog** [comment]
We are changing the nature of hyperdrive so resetting the issue queue. That said, the new version of hyperdrive will take this concern into consideration.
