### ISSUE TITLE
Install Docker when needed

### ISSUE THREAD

**Issue by soniktrooth** [lando/hyperdrive#3]
**Is your feature request related to a problem? Please describe.**
After being a naughty boy and upgrading docker I had to remove it to get back to the correct version. I tried running hyperdrive again and it could see that I needed docker but didn't actually install it. 

**Describe the solution you'd like**
Install docker if it's needed, regardless of whether Lando is present.

**Describe alternatives you've considered**
Heavy drinking, narcotics abuse.

**Comment by signosis** [comment]
> 
> **Describe alternatives you've considered**
> Heavy drinking, narcotics abuse.

Tried this and can report it does not solve the problem.
