### ISSUE TITLE
Spin off argv into its own repo

### ISSUE THREAD

**Issue by pirog** [lando/hyperdrive#31]
Now that your powers are growing its time to create your own full-lifecycle node module:

1. Create a new repo `lando/argv` to contain your `argv` module. It should be named `@lando/argv` in the `package.json`
2. Move over relevant things eg files and config and things from the `package.json` eg dependencies (there should be none), dev dependencies, scripts. 
3. Make sure the `package.json` is modified to reflect the current situation, remove any no-longer-needed things if you copied it from hyperdrive
4. Set up relevant node scripts for linting and unit testing
5. Set up relevant GitHub actions for linting and unit testing on pull requests
6. Set up relevant branch protection for `main` in the repo 
7. Set up relevant GitHub action to deploy the package to `npm` if a tag exists on the `main` branch
8. Set up a release command of some kind, see `yarn release` in hyperdrive and the `version-bump-prompt` module if you want to just do the same thing.
9. Set up a relevant CHANGELOG.md to keep track of things
10. Since we have 100% test coverage and docblocks in place i think its safe to just call this version `1.0.0`
11. Once we are deployed to npm we should remove the relevant things from hyperdrive and add `@lando/argv` as a dependency. Obviously update the require in `bin/hyperdrive` to point to the new thing.

**Comment by labboy0276** [comment]
@pirog I spun the npm issue off to the new argv repo.

Here is the PR to adjust this to the new repos: https://github.com/lando/hyperdrive/pull/32
